In [4]:
!pip install tensorflow

You should consider upgrading via the 'C:\Users\priya\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [10]:
import os
path = os. getcwd()
print(path)

c:\Users\priya\OneDrive - auist.net\Documents\GitHub\neural_algorithms\deep_learning_2022


In [14]:
#decode an image
import tensorflow as tf
image = "tensor_examples/rose.jpg"
image_open = open(image,'rb')
read_image = image_open.read()
image_decode = tf.image.decode_jpeg(read_image)
print(image_decode)
print(image_decode.shape)


tf.Tensor(
[[[121  74  56]
  [122  75  57]
  [126  75  56]
  ...
  [165 109  86]
  [167 111  88]
  [169 113  90]]

 [[127  78  61]
  [128  79  62]
  [132  81  62]
  ...
  [166 110  87]
  [168 112  89]
  [170 114  91]]

 [[134  83  66]
  [137  84  68]
  [142  86  69]
  ...
  [167 111  88]
  [169 112  92]
  [171 114  94]]

 ...

 [[  4  13  12]
  [  2  11  10]
  [  0   7   6]
  ...
  [114  88  73]
  [116  88  74]
  [117  89  75]]

 [[  7  13  11]
  [  3  12   9]
  [  0   9   6]
  ...
  [113  87  72]
  [115  87  73]
  [116  88  74]]

 [[ 17  18  12]
  [ 14  17  10]
  [  8  13   6]
  ...
  [114  88  73]
  [117  89  75]
  [119  91  77]]], shape=(265, 190, 3), dtype=uint8)
(265, 190, 3)


In [15]:
#tensor demo
#1D
import numpy as np
x = np.array([2,5,7])
print(x)
print("Dimension ", x.ndim)
print("Shape ", x.shape)

y = np.array([[2,5,7],[3,6,8]])
print(y)
print("Dimension ", y.ndim)
print("Shape ", y.shape)

z = np.array([[[1,3,5,6],[2,4,6,7],[1,2,3,4]],[[4,3,2,1],[7,9,11,12],[8,10,12,9]]])
print(z)
print("Dimension ", z.ndim)
print("Shape ", z.shape)


[2 5 7]
Dimension  1
Shape  (3,)
[[2 5 7]
 [3 6 8]]
Dimension  2
Shape  (2, 3)
[[[ 1  3  5  6]
  [ 2  4  6  7]
  [ 1  2  3  4]]

 [[ 4  3  2  1]
  [ 7  9 11 12]
  [ 8 10 12  9]]]
Dimension  3
Shape  (2, 3, 4)


In [16]:
#Simple operation to illustrate constant and variable
import tensorflow as tf
x = tf.constant(2)
y = tf.Variable(x+4)
#type(x)
#print(x)
total=x+y
#type(total)
print(total)


tf.Tensor(8, shape=(), dtype=int32)
